### ISSUE TITLE
Release strategy

### ISSUE THREAD

**Issue by JonasProgrammer** [elsid/resource_pool#27]
Hi,

so I got into the conan center EAP and would like to add `resource_pool` there. They have some restrictions regarding conanfiles accepted, but I'll try and keep it pretty close to what is given here in the repository.

One question remains: Do you actually ever plan on doing proper 'releases' of resource_pool, i.e. bumping the versions in the `CMakeLists.txt` or should this be considered a rolling release?

Depending on that, I'd either add the package with a version number or in a conan-specific `cci.yyyyMMdd` version format, which will allow consumers to rely on stable packages without taking the pseudoversion into account.

**Comment by elsid** [comment]
I don't think there is a need to setup versions. There is no active development on the project and no plans to have it. So rolling releases should be fine.
